let CompanyConfig =  {
    // 模块名称
    name:'公司管理',
    moduleType:'company',
    // 添加表单添加项
    addConfig:[
        {
            name:'公司名称',
            form_type:'input',
            placeholder:'请输入公司名称',
            key:'name',
            required:true
        },
        {
            name:'公司编码',
            form_type:'input',
            placeholder:'请输入公司编码',
            key:'code',
            required:true
        },
        {
            name:'联系人',
            form_type:'input',
            placeholder:'请输入联系人',
            key:'contacts',
            required:true
        },
        {
            name:'联系电话',
            form_type:'input',
            placeholder:'请输入联系电话',
            key:'phone',
            required:true
        },
        {
            name:'紧急联系人',
            form_type:'input',
            placeholder:'请输入紧急联系人',
            key:'emergent_contacts',
            required:true
        },
        {
            name:'紧急联系电话',
            form_type:'input',
            placeholder:'请输入紧急联系电话',
            key:'emergent_phone',
            required:true
        },
        {
            name:'公司类型',
            form_type:'select',
            placeholder:'请选择公司类型',
            key:'type',
            required:true
        },
        {
            name:'所在城市',
            form_type:'input',
            placeholder:'请选择所在城市',
            key:'area',
            required:true
        },
        {
            name:'电费费率（app）%',
            form_type:'input',
            placeholder:'请输入电费费率',
            key:'app_elec_discount',
            required:false
        },
        {
            name:'服务费费率（app）%',
            form_type:'input',
            placeholder:'请输入服务费费率',
            key:'app_serve_discount',
            required:false
        },
        {
            name:'电费费率(微信)%',
            form_type:'input',
            placeholder:'请输入电费费率',
            key:'wx_elec_discount',
            required:false
        },
        {
            name:'服务费费率（app）%',
            form_type:'input',
            placeholder:'请输入服务费费率',
            key:'wx_serve_discount',
            required:false
        },
        {
            name:'电费费率(卡)%',
            form_type:'input',
            placeholder:'请输入电费费率',
            key:'card_elec_discount',
            required:false
        },
        {
            name:'服务费费率(卡)%',
            form_type:'input',
            placeholder:'请输入服务费费率',
            key:'card_serve_discount',
            required:false
        },
        {
            name:'备注',
            form_type:'input',
            placeholder:'请输入备注',
            key:'remarks',
            required:false
        },
        {
            name:'详细地址',
            form_type:'input',
            placeholder:'请输入详细地址',
            key:'address',
            required:true
        },
        {
            name:'上级公司',
            form_type:'select',
            placeholder:'请选择上级公司',
            key:'parent',
            required:true
        },
    ],
    // 筛选配置
    filterConfig:[
        {
            filter_name:'公司',
            filter_placeholder:'公司名称',
            filter_key:'enterprise_id',
            filter_type: 'write_select'
        },
        {
            filter_name:'公司编码',
            filter_placeholder:'公司编码',
            filter_key:'query_code',
            filter_type: 'write'
        },
        {
            filter_name:'上级公司',
            filter_placeholder:'上级公司',
            filter_key:'query_code',
            filter_type: 'write_select'
        },
        {
            filter_name:'所在城市',
            filter_key:'query_code',
            filter_type: 'cascader',
            filter_placeholder:'请选择所在城市'
        },
        {
            filter_name:'所在城市',
            filter_placeholder:'公司等级',
            filter_key:'公司等级',
            filter_type: 'select',
            selet_options:[
                {
                    key:'1',
                    name:'一级'
                },
                {
                    key:'2',
                    name:'二级'
                },
                {
                    key:'3',
                    name:'三级'
                }
            ]
        }
    ],
    // 列表内容
    listColumns:[
        // {
        //     title:'序号',
        //     dataIndex:'index',
        //     key:'index',
        //     render: (index) => {
		// 	    return index + 1
		//     },
        // },

        {
            title:'公司名称',
            dataIndex:'name',
            key:'name'
        },
        {
            title:'公司编码',
            dataIndex:'code',
            key:'code'
        },
        {
            title:'上级公司',
            dataIndex:'parent_name',
            key:'parent_name'
        },
        {
            title:'公司等级',
            dataIndex:'level',
            key:'level'
        },
        {
            title:'联系人',
            dataIndex:'contacts',
            key:'contacts'
        },
        {
            title:'联系电话',
            dataIndex:'phone',
            key:'phone'
        },
        {
            title:'详细地址',
            dataIndex:'address',
            key:'address'
        },
        {
            title:'创建时间',
            dataIndex:'created_at',
            key:'created_at'
        }
    ]
}
export default CompanyConfig
